### ISSUE TITLE
Vault command doesn't overwrite application variables

### ISSUE THREAD

**Issue by sjparkinson** [Financial-Times/n-gage#15]
Calling `make .env-vault` _should_ merge application variables with our shared variables, with any application variables of the same name overwriting any shared variables.

Currently we'll just end up with a `.env` file with two values for the same key.

**Comment by quarterto** [comment]
@sjparkinson does this still happen? can't say i've noticed it

**Comment by sjparkinson** [comment]
Don't think it's a major issue anywhere if it does. Would assume it still does though. Happy for this to be closed as I've not heard of any complaints.
