### ISSUE TITLE
Duplication of build commands between n-gage and nui build

### ISSUE THREAD

**Issue by adgad** [Financial-Times/n-gage#150]
We have a `make build(-production)` task in n-gage that does the following:
* make __about.json
* webpack build
* (previously) haikro build

There is also an `nui build` task in n-ui which does basically the same in Javascript (plus maybe more n-ui stuff?)

This is weird and confusing.

**Comment by quarterto** [comment]
@i-like-robots could you weigh in on this? do you know what the purpose of the `nui` commands is vs the make targets? does pagekit mean we can close this?

**Comment by i-like-robots** [comment]
Removed in #219
