### ISSUE TITLE
Associate our commits with a sentry release

### ISSUE THREAD

**Issue by robsquires** [Financial-Times/n-gage#174]
**Why?**
Sentry often flags issues that have previously been resolved..likely due to old cached JS being out there in the wild. Would be gr8 if it didn't.

**What?**
Associate our commits with a release in sentry. We've done this for AMP /cc @quarterto 

https://docs.sentry.io/workflow/releases/?_ga=2.43259109.1933246660.1549367863-429723123.1540296077%3F_ga&platform=javascript#associate-commits-with-a-release

**Comment by robsquires** [comment]
@adambraimbridge @quarterto 📝

**Comment by quarterto** [comment]
[AMP's implementation](https://github.com/Financial-Times/google-amp/blob/f522d994bb3c1677d8c9ccf1fa5af7c6a3b53241/scripts/build/release.js#L161-L169), which is [this library of mine](https://gist.github.com/quarterto/72bfc9ae2f1aab196ac870e96a69c350) which is just a boneless version of [sentry-cli](https://docs.sentry.io/cli/#sentry-cli) which didn't exist at the time. we should just use the cli, via n-gage
