### ISSUE TITLE
Better docs for breaking changes

### ISSUE THREAD

**Issue by debugwand** [Financial-Times/n-gage#179]
https://github.com/Financial-Times/n-gage/releases/tag/v3.0.0 links to a page about heroku deploys, but the changes made also affect apps that don't run on heroku. 

The breaking changes that affect both serverless and heroku apps are in the section that is about canary, and are buried quite far down in https://github.com/Financial-Times/next/wiki/Heroku-review-apps-deployment so I'd already stopped reading as I didn't think those sections would apply.

This was the fix:
https://github.com/Financial-Times/next-podcast-poller/commit/8f68abc85b50c8dd5b80a36bb1a12cf7b188017a

**Comment by quarterto** [comment]
sorry for the churn, we were pretty focused on heroku repos for this release. i've added [a section](https://github.com/Financial-Times/next/wiki/Heroku-review-apps-deployment#non-heroku-repositories) to that migration guide. ideally, i'd rename the document, but it's linked to from a lot of places, and Github wiki doesn't handle redirects well (you can link to the new page, but if the original link had an anchor that context gets lost). how's that look?
