### ISSUE TITLE
Deprecation warning for experimentalObjectRestSpread

### ISSUE THREAD

**Issue by sjparkinson** [Financial-Times/n-gage#183]
```
[ESLINT_LEGACY_OBJECT_REST_SPREAD] DeprecationWarning:

The 'parserOptions.ecmaFeatures.experimentalObjectRestSpread' option is deprecated.

Use 'parserOptions.ecmaVersion' instead. (found in ".eslintrc.js")
```

https://github.com/Financial-Times/n-gage/blob/0ffe8f4db5ba5a04c3fd9210fd13cfcbbe8fab35/dotfiles/.eslintrc.js#L12-L14

**Comment by OttlikG** [comment]
Bumping to 2018 solved the issue for me.
Node 8.15 support this functionality so I think we are safe to bump to 2018
https://node.green/#ES2018-features-object-rest-spread-properties

**Comment by OttlikG** [comment]
If we start supporting ecmascript 2018 with linting rules the best approach to also update the circleci to use the appropriate version.
https://github.com/CircleCI-Public/circleci-dockerfiles/tree/master/node/images/8.15.0-stretch
When I used rest/spread in one of my lib n-ui started failing because it used the standard docker image (circleci/node:8-browsers) and I didn't used babel to transile my code.

**Comment by sjparkinson** [comment]
> When I used rest/spread in one of my lib n-ui started failing because it used the standard docker image (circleci/node:8-browsers) and I didn't used babel to transile my code.

We _should_ be using `circleci/node:8.15.1-browsers` almost everywhere actually. There maybe a few repos out there that haven't been updated yet, but we should be pinned to a specific version of node.

You note using the `-stretch` image, does that have any changes in it?

**Comment by OttlikG** [comment]
I've seen some repo using that older version:
https://github.com/search?p=3&q=org%3AFinancial-Times+image%3A+circleci%2Fnode%3A8-browsers&type=Code

as n-ui still use that old version.
https://github.com/Financial-Times/n-ui/blob/master/.circleci/config.yml#L9

**Comment by sjparkinson** [comment]
I think you're might be miss-reading what the version means.

Currently, given that 8.15.1 is the latest release, for the two Docker images the following is true.

```
circleci/node:8-browsers === circleci/node:8.15.1-browsers
```

The way CircleCI publish their Docker images means that `circleci/node:8-browsers` is kinda like saying in `package.json`:

```json
{
  "engines": {
    "node": "^8.0.0"
  }
}
```

Which would install the latest version of Node.js.

I can't actually find any documentation the back this up however! But here's the two side by side after using `docker pull <image>` and `docker images`, note that they share the same image id.

```
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
circleci/node       8-browsers          6ac62eadb66c        16 hours ago        1.99GB
circleci/node       8.15.1-browsers     6ac62eadb66c        16 hours ago        1.99GB
```

**Comment by sjparkinson** [comment]
Given that, I don't think we need to make any changes to our CircleCI configuration before updating our eslint configuration 🎉

**Comment by OttlikG** [comment]
Yes, make sense.
