### ISSUE TITLE
n-gage is too tightly coupled to n-test

### ISSUE THREAD

**Issue by jamesnicholls** [Financial-Times/n-gage#255]
I have found it difficult to use `n-test` and Puppeteer to run smoke tests. I would like to be able to choose alternative frameworks to run automated tests, such as Cypress. However `n-gage` is tightly coupled to `n-test`, and `n-test` is coupled to Puppeteer, making it difficult to use any other framework.

[Some n-gage tasks](https://github.com/Financial-Times/n-gage/blob/9744dac1abfff71f931c0d71869c202801fa7a71/src/tasks/review-app.mk#L37-L45) call run an app's smoke tests by running `make smoke`, which is fairly small and easy to override. However the `deploy-staging` task calls `n-test` [directly](https://github.com/Financial-Times/n-gage/blob/9744dac1abfff71f931c0d71869c202801fa7a71/src/tasks/deploy.mk#L95). As `deploy-staging` does a lot of other stuff, overriding it completely is a potential maintenance burden.

**Comment by apaleslimghost** [comment]
thanks for this James! we're currently in the early stages of development on n-gage's successor, so we're only doing maintanence and critical fixes from now on.

for now, you could work around this by adding a (mostly) empty `smoke.js` (i think `module.exports = []` would be enough).

we are aiming to untangle a lot of this kind of tight coupling in the replacement, so hopefully we can fix this for you in the future. would you be at all interested in helping us test that soon?
