### ISSUE TITLE
Make .env-vault false positives

### ISSUE THREAD

**Issue by adambraimbridge** [Financial-Times/n-gage#57]
![image](https://user-images.githubusercontent.com/224547/28019673-a14bae7e-6579-11e7-9f3a-973202a9775d.png)

Expectation: If `.env-vault` doesn't generate a `.env` file, output something more like 
```
✓ .env-vault: No secrets found. Is your app in the next service registry?
```
instead of
```
✓ .env-vault done
```

**Comment by quarterto** [comment]
looks like this was fixed by #66
